name: LAB7_417477_test

on:
  push:
    branches:
      - roboczy

jobs:
  # Równoległe joby dla każdej z bazowych funkcji
  test_dodawanie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        # Użyj working-directory, aby określić katalog dla tej komendy
        run: pip install -r requirements.txt
        working-directory: ./LAB7/env_417477 # <--- DODANO TO
      - name: Run test_dodawanie
        # Użyj working-directory, aby określić katalog dla tej komendy
        run: pytest test_dodawanie.py
        working-directory: ./LAB7/env_417477 # <--- DODANO TO

  test_odejmowanie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./LAB7/env_417477 # <--- DODANO TO
      - name: Run test_odejmowanie
        run: pytest test_odejmowanie.py
        working-directory: ./LAB7/env_417477 # <--- DODANO TO

  test_mnozenie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./LAB7/env_417477 # <--- DODANO TO
      - name: Run test_mnozenie
        run: pytest test_mnozenie.py
        working-directory: ./LAB7/env_417477 # <--- DODANO TO

  test_dzielenie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./LAB7/env_417477 # <--- DODANO TO
      - name: Run test_dzielenie
        run: pytest test_dzielenie.py
        working-directory: ./LAB7/env_417477 # <--- DODANO TO

  # Nowy job dla testów funkcji Pandas, uruchamiany po zakończeniu wszystkich poprzednich
  new_tests:
    runs-on: ubuntu-latest
    needs: [test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./LAB7/env_417477 # <--- DODANO TO
      - name: Run new pandas tests
        run: pytest test_pandas_funkcje.py
        working-directory: ./LAB7/env_417477 # <--- DODANO TO